name: CI
on: [push, pull_request]
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable
      - run: rustup default stable
      - run: rustup component add clippy rustfmt
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: ./test.sh || true
